### ISSUE TITLE
`%` in cv01

### ISSUE THREAD

**Issue by Gn3po4g** [subframe7536/maple-font#245] opened 2024-09-13 07:46 UTC
开启cv01后`%`字符没有变化，是否正常？

![image](https://github.com/user-attachments/assets/2e34ad21-1273-40d9-864f-cebd105bf7f7)
👆与其他字符比较

**Comment by subframe7536** [comment] 2024-09-13 10:02
as is. 文档里写了

但是现在想想可以考虑尝试实现一下

**Comment by subframe7536** [comment] 2024-10-01 09:47
在v7-beta27中实现了

**Comment by Gn3po4g** [comment] 2024-10-03 05:41
<3

**Comment by Gn3po4g** [comment] 2024-10-14 01:49
突然发现`%`比其他符号细了一点：
![图片](https://github.com/user-attachments/assets/33f12f6a-5b00-4e67-a299-d309011d0e01)

**Comment by subframe7536** [comment] 2024-10-14 01:56
JetBrains Mono 也干了(

**Comment by Gn3po4g** [comment] 2024-10-14 02:01
> JetBrains Mono 也干了(
> 
> ![mmexport1728871022870.png](https://private-user-images.githubusercontent.com/78338239/376089403-4b8af4eb-d765-4a9e-a3bc-a0553178d160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzE0MDUsIm5iZiI6MTcyODg3MTEwNSwicGF0aCI6Ii83ODMzODIzOS8zNzYwODk0MDMtNGI4YWY0ZWItZDc2NS00YTllLWEzYmMtYTA1NTMxNzhkMTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAxNTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNWNlYTc1ZjNkMTM2ZjRjMDVhZTQwM2EzZWRhYjA1ZmEzNTU4MTVmNjlmMTNkNWIzZTU2OTkwMDFiOTc2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zqmd9-tl9U6wMuxSnpj_5w60p2abJYSCQ292EzcT6d4)

可能是因为jb mono里的线比较细？
不过感觉如果%加粗的话可能会有点挤。

**Comment by Nagidrop** [comment] 2024-10-27 06:48
> Suddenly found a little thinner than the other symbols:`%` ![Image](https://private-user-images.githubusercontent.com/92096903/376088214-33f12f6a-5b00-4e67-a299-d309011d0e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTExNTQsIm5iZiI6MTczMDAxMDg1NCwicGF0aCI6Ii85MjA5NjkwMy8zNzYwODgyMTQtMzNmMTJmNmEtNWIwMC00ZTY3LWEyOTktZDMwOTAxMWQwZTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA2MzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyY2IzNWU0MzBhYTE4Njg2ZGFhZTFiYmM5OGNiYmY2Y2IxOTJhZWY2MWZhNzc2NTMzODE3ODY5MGYxOTlkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z6PpOgX-K24kOKEI-qVaFuKGtTrpjvcuNPvrDpiJ3eU)

It seems that you and me both easily notice the thin-characters :P I also noticed this. The `%` sign looks thinner like 1 less weight (feels like Regular weight at Medium)

In below image it's more noticable that the bold `%` sign (first line) matches the Medium `$` and the Medium `%` (second line) looks thinner.

![thin_percent](https://github.com/user-attachments/assets/4b0e748f-fca6-49a5-b1a1-f3b92acb2009)

**Comment by subframe7536** [comment] 2024-10-27 06:57
![recording](https://github.com/user-attachments/assets/ac9deda3-4b35-4bc3-8672-d5eb50c9b745)
Just included in next beta version, reference from `JetBrains Mono` 's glyphs

**Comment by Nagidrop** [comment] 2024-10-27 07:07
> ![recording](https://private-user-images.githubusercontent.com/78338239/380474309-ac9deda3-4b35-4bc3-8672-d5eb50c9b745.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTI4NzEsIm5iZiI6MTczMDAxMjU3MSwicGF0aCI6Ii83ODMzODIzOS8zODA0NzQzMDktYWM5ZGVkYTMtNGIzNS00YmMzLTg2NzItZDVlYjUwYzliNzQ1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA3MDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMDc1Y2JhOWFhYzBiNzJiNjg5NTRkMDRiNjE4NDdlMTgyMTYwZGFlMGYxZWViNTBjOWUzM2IzYjU2ZWE2OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.70k3Vw_U5iKM7XXPv4JphJo7SqaFyXhTirbRxSrURyU) [ ![recording](https://private-user-images.githubusercontent.com/78338239/380474309-ac9deda3-4b35-4bc3-8672-d5eb50c9b745.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTI4NzEsIm5iZiI6MTczMDAxMjU3MSwicGF0aCI6Ii83ODMzODIzOS8zODA0NzQzMDktYWM5ZGVkYTMtNGIzNS00YmMzLTg2NzItZDVlYjUwYzliNzQ1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA3MDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMDc1Y2JhOWFhYzBiNzJiNjg5NTRkMDRiNjE4NDdlMTgyMTYwZGFlMGYxZWViNTBjOWUzM2IzYjU2ZWE2OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.70k3Vw_U5iKM7XXPv4JphJo7SqaFyXhTirbRxSrURyU) ](https://private-user-images.githubusercontent.com/78338239/380474309-ac9deda3-4b35-4bc3-8672-d5eb50c9b745.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTI4NzEsIm5iZiI6MTczMDAxMjU3MSwicGF0aCI6Ii83ODMzODIzOS8zODA0NzQzMDktYWM5ZGVkYTMtNGIzNS00YmMzLTg2NzItZDVlYjUwYzliNzQ1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA3MDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMDc1Y2JhOWFhYzBiNzJiNjg5NTRkMDRiNjE4NDdlMTgyMTYwZGFlMGYxZWViNTBjOWUzM2IzYjU2ZWE2OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.70k3Vw_U5iKM7XXPv4JphJo7SqaFyXhTirbRxSrURyU) [ ](https://private-user-images.githubusercontent.com/78338239/380474309-ac9deda3-4b35-4bc3-8672-d5eb50c9b745.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTI4NzEsIm5iZiI6MTczMDAxMjU3MSwicGF0aCI6Ii83ODMzODIzOS8zODA0NzQzMDktYWM5ZGVkYTMtNGIzNS00YmMzLTg2NzItZDVlYjUwYzliNzQ1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA3MDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMDc1Y2JhOWFhYzBiNzJiNjg5NTRkMDRiNjE4NDdlMTgyMTYwZGFlMGYxZWViNTBjOWUzM2IzYjU2ZWE2OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.70k3Vw_U5iKM7XXPv4JphJo7SqaFyXhTirbRxSrURyU) Just included in next beta version, reference from `JetBrains Mono` 's glyphs

That looks much better. I can't wait to try it out :D

**Comment by Nagidrop** [comment] 2024-11-05 05:17
Sorry to bump this back again. After a week working with new `%` in cv01, I feel it's still a little short to perfection (although looked better than before). The 2 little `o` on the diagonal look right, but the slash `/` inside `%` is quite thin. 

Here is a comparison to JetBrains Mono, you can see it's less balanced on Maple Mono's side.

| Maple Mono |  JetBrains Mono |
:---------------:|:-------------------:
![Maple_Mono](https://github.com/user-attachments/assets/42898385-83c5-4d62-bfd3-5b561a32e5c5) |  ![JetBrains_Mono](https://github.com/user-attachments/assets/29ddbc69-f4d7-41b8-82c2-fb515eb484cb)

I think making the slash width slightly bigger, similar to the middle slash of dollar sign `$` would make it perfect.
![just_like_dollor](https://github.com/user-attachments/assets/2c56d056-a426-48e2-af5c-e85bc6e262d7)

Also in the normal variant, glyph sizes of 2 `o` and slash `/` look more balanced itself and in comparison to other characters.

![normal_var](https://github.com/user-attachments/assets/d4531117-f1b2-4901-9b8f-ec424c17eea5)

Maybe we could slightly increase the glyph sizes of 2 `o` and slash `/` of the old percentage `%` to achieve the same balance effect?

![thin_percent](https://github.com/user-attachments/assets/4b0e748f-fca6-49a5-b1a1-f3b92acb2009)

**Comment by subframe7536** [comment] 2024-11-06 01:38
Valuable suggestion. I will share the progress here

**Comment by subframe7536** [comment] 2024-11-09 03:22
![recording](https://github.com/user-attachments/assets/1723174a-642c-47a6-bae1-696fbc473811)

**Comment by Nagidrop** [comment] 2024-11-09 13:56
I just try it out on [MuTsunTsai's fontfreeze](https://mutsuntsai.github.io/fontfreeze/) and it looks amazing. Balance and weight issues are both resolved across all weights. Your decision to rotate the slash `/` clock-wise a little also makes it looks better.

Here are some sanity checks for Medium weight

| Old slash |  New slash |
:-----------:|:------------:
![slash_old](https://github.com/user-attachments/assets/ce65473b-56df-47d4-947d-201efa748675) | ![slash_new](https://github.com/user-attachments/assets/ca05773d-3de5-476e-80cf-34dadb0a4b35)

| Maple Mono (old) |  Maple Mono (new) |
:---------------:|:-------------------:
![Maple_Mono](https://github.com/user-attachments/assets/42898385-83c5-4d62-bfd3-5b561a32e5c5) |  ![Maple_Mono_fix](https://github.com/user-attachments/assets/1a44bf8d-c318-4b18-b665-52a96b38d45b)

| Maple Mono (old) |  Maple Mono (new) |
:---------------:|:-------------------:
![thin_percent](https://github.com/user-attachments/assets/4b0e748f-fca6-49a5-b1a1-f3b92acb2009) | ![Maple_Mono_fix_JupyterLite png](https://github.com/user-attachments/assets/e35fbe9f-36d3-478e-8104-c71bfe5aac48)

In JupyterLite, I notice the operator `%` weight on first line looks much bolder than even the ExtraBold one. My guess is JupyterLab forced the "bold" variant of "Medium" weight that exceeded all defined weights? It's a non-issue for me but the previous version's imbalance `%` didn't have this, so I think it's worth mentioning. 

Also, I used the font generated from [MuTsunTsai's fontfreeze](https://mutsuntsai.github.io/fontfreeze/) for the checks. I tried to build the font locally with `cv01` by replacing `MapleMono[wght]-VF.ttf` in `source` folder but it throws this error (might be because I don't have the new `MapleMono[wght].glyphs` and `MapleMono[wght].vfc` files?):
```
[ ERROR    ] 'NoneType' object has no attribute 'toUnicode'
```

**Comment by subframe7536** [comment] 2024-11-09 15:06
> In JupyterLite, I notice the operator `%` weight on first line looks much bolder than even the ExtraBold one. My guess is JupyterLab forced the "bold" variant of "Medium" weight that exceeded all defined weights? It's a non-issue for me but the previous version's imbalance `%` didn't have this, so I think it's worth mentioning.

Are you using variable version in JupyterLite? There may exist some unexpected differences between using variable font and using static font


> Also, I used the font generated from [MuTsunTsai's fontfreeze](https://mutsuntsai.github.io/fontfreeze/) for the checks. I tried to build the font locally with `cv01` by replacing `MapleMono[wght]-VF.ttf` in `source` folder but it throws this error (might be because I don't have the new `MapleMono[wght].glyphs` and `MapleMono[wght].vfc` files?):

I just use `.ttf` to build release files. And now I push the changes to the repo. You can check it out

**Comment by Nagidrop** [comment] 2024-11-09 15:52
> I just use `.ttf` to build release files. And now I push the changes to the repo. You can check it out

The new script worked well. I diff-ed 2 folders and found `regular.fea`, `feature.py` are also different, so 1 of the files could have caused it.

> Are you using variable version in JupyterLite? There may exist some unexpected differences between using variable font and using static font

I use only static font there. I tried building Variable with `cv01` before but not successful, was about to create an issue until I saw you noted that it didn't support freezing features, so I think that's still in development. I also use normal `.ttf` instead of autohint to avoid discrepancies. 

Btw fonts built using the new script still has the problem in JupyterLite. Would you mind checking how the `%` operator highlight in VSCode looks like? I also checked in Notepad++ and it looks similar to JupyterLab:

![too_bold_percent](https://github.com/user-attachments/assets/38c75d51-60bd-423e-a9b7-d5c9c03caa03)

**Comment by subframe7536** [comment] 2024-11-10 02:35
Seems correctly rendered 
![recording](https://github.com/user-attachments/assets/5e367087-f737-4a7f-a822-dd2ffd99a364)

**Comment by Nagidrop** [comment] 2024-11-16 06:58
I just did some quick checks in JupyterLite and Notepad++.

In JupyterLite, other fonts `%` are also bold

| Maple Mono |  Fira Code | JetBrains Mono |
:---------------:|:-------------------:|:-------------------:
![Jupyter_Maple](https://github.com/user-attachments/assets/e9e22de0-6957-4de8-9b3a-50492859db6a) | ![Jupyter_Fira](https://github.com/user-attachments/assets/0284a040-3b60-4aec-a330-25faf4824435) | ![Jupyter_JetBrains](https://github.com/user-attachments/assets/98467c06-c517-4863-a46e-a640eeceb41f)

In Notepad++, others `%` seem to not render correctly (not bold)

| Maple Mono |  Fira Code | JetBrains Mono |
:---------------:|:-------------------:|:-------------------:
![Notepad_Maple](https://github.com/user-attachments/assets/b6938cb1-95f9-45e9-90bc-39eab82e7d3d) | ![Notepad_Fira](https://github.com/user-attachments/assets/1c769b3d-3199-4c83-8b67-c7cd233170e5) | ![Notepad_JetBrains](https://github.com/user-attachments/assets/adca4ddc-223f-4773-91c7-6ad980d6580c)

The checks showed that the bold `%` issue can be ignored.

Also, you might also notice in Notepad++, the top and bottom of the slash `/` looks flatter (like JetBrains Mono). It's Notepad++ problem, caused by Notepad++ duplicated `%` sideways:

https://github.com/user-attachments/assets/79c59584-3aee-4c9e-adf2-8d84224263d1

Though at smaller font sizes/weights, the slash `/` in `%` does look a little flat on top and bottom. Looking closely, its curve is less symmetric compared to the old one (before the fix). I think making it symmetric again can eliminate the "flat" feeling. 

I'd love to hear your perspective. Aside from that everything else is awesome :D

**Comment by subframe7536** [comment] 2024-11-17 13:06
I think I should make it symmetric. Other glyphs like `>` or default `%` are designed in that way

![PixPin_2024-11-17_21-03-46](https://github.com/user-attachments/assets/7c56344c-3013-40e4-a0f9-8bdbea92bb1f)

**Comment by Nagidrop** [comment] 2024-11-18 15:53
> I think I should make it symmetric. Other glyphs like `>` or default `%` are designed in that way
> 
> ![PixPin_2024-11-17_21-03-46](https://private-user-images.githubusercontent.com/78338239/386960584-7c56344c-3013-40e4-a0f9-8bdbea92bb1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDUyMzIsIm5iZiI6MTczMTk0NDkzMiwicGF0aCI6Ii83ODMzODIzOS8zODY5NjA1ODQtN2M1NjM0NGMtMzAxMy00MGU0LWEwZjktOGJkYmVhOTJiYjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE1NDg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YTMyNzU3ODg2NTM5NTRjYmZiZGMzYWMxMDU1Y2ZmYzQ1ZWM2ZWNhMWVmY2EzYWJhOGNiZWEyNDliZGZlZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gCNeEvLgWj6Gxgj9B32DgBnmM1bmfGfDsTTBpiX5aPE)

It looks promising to me. I'm eager to try it in action :D

**Comment by subframe7536** [comment] 2024-11-18 16:06
I planned to release beta30 last weekend, but [an annoying bug](https://x.com/subframe7536/status/1858535101640159738) prevented me. 

There is a draft one that already include `%` update: https://github.com/subframe7536/maple-font/releases/download/untagged-32dd7a0d48d5ef5d24ed/MapleMono-Variable.zip

**Comment by Nagidrop** [comment] 2024-11-18 17:43
> I planned to release beta30 last weekend, but [an annoying bug](https://x.com/subframe7536/status/1858535101640159738) prevented me.
> 
> There is a draft one that already include `%` update: https://github.com/subframe7536/maple-font/releases/download/untagged-32dd7a0d48d5ef5d24ed/MapleMono-Variable.zip

That's such an annoying bug. If I'm not wrong JetBrains IDEs have different font rendering from others. You may need to contact JetBrains to get it fixed more easily.

Regarding the new draft version, I possibly don't have permission to download it:

![notfound](https://github.com/user-attachments/assets/9fff1345-5810-45c9-af05-529ee7f868d7)

Btw I'm just kinda excited for the new change by saying "eager". I don't want you to hurry up or anything, please just take your time, upload the new one at your convenience.

**Comment by subframe7536** [comment] 2024-11-19 03:35
> You may need to contact JetBrains to get it fixed more easily.

I will have no expectation on this until they implement OpenType feature settings 😇. Their branded font have OpenType features and their products can't open it...

Try it here: [MapleMono-Variable.zip](https://github.com/user-attachments/files/17808893/MapleMono-Variable.zip)

**Comment by Nagidrop** [comment] 2024-11-20 13:03
> > You may need to contact JetBrains to get it fixed more easily.
> 
> I will have no expectation on this until they implement OpenType feature settings in IDEA's setting panel😇. Their branded font have OpenType features and their products can't enable it...
> 
> Try it here: [MapleMono-Variable.zip](https://github.com/user-attachments/files/17808893/MapleMono-Variable.zip)

It's funny when their font doesn't have all of features inside their own ecosystem. If so then do you plan on releasing the next beta without fixing it? It's still "beta" so an early warning should suffice in my opinion, if you hestitate on that.

Anyway, the new `%` looks stunning. There's no more "flat" feeling, the symmetry does pay off. The slash is slightly shorter, but I don't think anyone will notice, unless they captured screenshots at high font sizes and tried to tell the difference (like me :P)

| Old `/` | New `/` |
:---------------:|:-------------------:
![percent_old](https://github.com/user-attachments/assets/57985e48-3f29-4ee2-8bb2-290e85b6ae31) | ![percent_new](https://github.com/user-attachments/assets/06c11944-860e-4cd5-a52b-cc166ee0902a)

I don't think I have any further suggestions at this point. The `%` is pretty much flawless, if not perfect. Thank you for accepting my idea to change it and improve along :D

**Comment by subframe7536** [comment] 2024-11-23 12:25
Release in v7.0-beta30

**Closed by subframe7536** 2024-11-23 12:25 UTC
